title: HomeKit Builds & Reviews
description: A site dedicated to building a smart, sensible home using Apple's HomeKit.
show_downloads: false

url: "https://homekitbuilds.mrrooni.com" # change this to the base hostname & protocol for your site


# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Michael Fey
image: /assets/images/HomeKitBuildsIcon.png
twitter:
  username: mrrooni

plugins:
  - jekyll-target-blank
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
target-blank:
    rel: nofollow

header_page_refs: ['accessories']
